import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { CartProvider } from "@/lib/cart-context";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const supreme = localFont({
  src: "../public/fonts/Supreme-Regular.otf",
  variable: "--font-body",
  display: "swap",
});

const nunito = localFont({
  src: "../public/fonts/Nunito-ExtraBold.otf",
  variable: "--font-heading",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        supreme.variable,
        nunito.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full flex flex-col bg-[#FBF7F2]">
        {" "}
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
